# Server configuration
server:

# Message configuration
message:
  lang: "en"
  prefix: "<gray>[<aqua><bold>FFaction</bold><gray>] "

# Storage configuration
storage:
  # Available types: MYSQL, SQLITE, YAML
  type: "YAML"

  # MySQL configuration
  mysql:
    host: "localhost"
    port: 3306
    database: "ffaction"
    username: "root"
    password: ""
    tablePrefix: "ffaction_"

  # SQLite configuration
  sqlite:
    filename: "ffaction/data"
    tablePrefix: "ffaction_"

  # YAML configuration
  yaml:
    filename: "ffaction/data.yml"