# Faction
faction:
  maxMembers: 20
  maxPower: 10
  minPower: 0
  maxClaims: 50
  powerPerLand: 1

# Server configuration
server:

# Message configuration
message:
  lang: "en"
  prefix: "<gray>[<aqua><bold>FFaction</bold><gray>] "

# Storage configuration
storage:
  # Available types: MYSQL, SQLITE, YAML
  type: "YAML"

  # MySQL configuration
  mysql:
    host: "localhost"
    port: 3306
    database: "ffaction"
    username: "root"
    password: ""
    tablePrefix: "ffaction_"
